### PR TITLE
Conjure plus

### PR DESCRIPTION
**Pull request by ogabek96**
Added `%%conjure+` magic:

- `%%conjure+` stores previous runs and it is used for incremental model building
- `%%conjure` magic is changed to run the model always from the beginning

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Why did you close this  PR @ogabek96?

**Comment by ozgurakgun** [comment]
so `register_magic_function` let's you set a `magic_name` that isn't necessarily a valid python identifier. good find! I remember we could figure this out during your project or else `conjure_settings` would probably have been called `conjure-settings`!

**Comment by ozgurakgun** [comment]
The tests need updating, of course.

**Comment by ogabek96** [comment]
> so `register_magic_function` let's you set a `magic_name` that isn't necessarily a valid python identifier. good find! I remember we could figure this out during your project or else `conjure_settings` would probably have been called `conjure-settings`!



> Why did you close this PR @ogabek96?
I wasn't ready to merge, so I closed. We can leave it open if it okay

**Comment by ozgurakgun** [comment]
Yes, let's keep it open please.

**Comment by ozgurakgun** [comment]
Hi @ogabek96 - I just remembered this. What did you want to do before merging this? Do you mind if I continue working on adding this if you don't have the time?

**Comment by ogabek96** [comment]
Didn't have a chance to work on this. I think there are only updating tests left in this PR. Yeah you can continue on this if you want

**Comment by ozgurakgun** [comment]
Closed, see #33

**Pull request closed without merging**
